language: java

before_script:
  - export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
  
jdk:
  - oraclejdk8

install:
  - sudo apt-get install -y maven

script:
  - cd SDS
  - mvn clean package install
