package com.sds.service.common.enumerados;

public enum Atributo {

	USUARIO, PASSWD_USUARIO, DNI_PERSONA, NOMBRE, APELLIDOS_PERSONA, FECHA_NACIMIENTO, EMAIL, TELEFONO, DIRECCION,
	CIF_EMPRESA, ROL_NAME, ROL_DESCRIPTION, ACCION_NAME, ACCION_DESCRIPTION;
}
