package com.sds.service.common.enumerados;

public enum Atributo {

	USUARIO, PASSWD_USUARIO, DNI_PERSONA, DNI_USUARIO, NOMBRE, APELLIDOS_PERSONA, FECHA_NACIMIENTO, EMAIL, TELEFONO,
	DIRECCION, CIF_EMPRESA, ROL_NAME, ROL_DESCRIPTION, ACCION_NAME, ACCION_DESCRIPTION, FUNCIONALIDAD_NAME,
	FUNCIONALIDAD_DESCRIPTION, TITULO_NOTICIA, TEXTO_NOTICIA, FECHA_NOTICIA, NOMBRE_OBJETIVO, DESCRIPCION_OBJETIVO,
	TEXTO_RESPUESTA_POSIBLE, NOMBRE_PLAN, DESCRIP_PLAN, FECHA_PLAN, NOMBRE_PROCEDIMIENTO, DESCRIP_PROCEDIMIENTO,
	FECHA_PROCEDIMIENTO;
}
