package com.sds.service.common.enumerados;

public enum Funcionalidad {

	LOGIN, REGISTRAR, GESTION_ROLES, GESTION_ACCIONES, GESTION_FUNCIONALIDADES, GESTION_USUARIOS, GESTION_PERSONAS,
	RECUPERAR_PASS, GESTION_EMPRESAS, GESTION_NOTICIAS, GESTION_OBJETIVOS, GESTION_RESPUESTA_POSIBLE;
}
