package com.sds.service.common;

public class CodigosMensajes {

	public static final String LOGIN_USUARIO_VACIO = "LOGIN_USUARIO_VACIO";
	public static final String LOGIN_ALFANUMERICO_INCORRECTO = "LOGIN_ALFANUMERICO_INCORRECTO";
	public static final String LOGIN_MENOR_QUE_3 = "LOGIN_MENOR_QUE_3";
	public static final String LOGIN_MAYOR_QUE_45 = "LOGIN_MAYOR_QUE_45";

	public static final String PASS_USUARIO_VACIO = "PASS_USUARIO_VACIO";
	public static final String PASS_ALFANUMERICO_INCORRECTO = "PASS_ALFANUMERICO_INCORRECTO";
	public static final String PASS_MENOR_QUE_3 = "PASS_MENOR_QUE_3";
	public static final String PASS_MAYOR_QUE_45 = "PASS_MAYOR_QUE_45";

	public static final String LOGIN_USUARIO_INCORRECTO = "LOGIN_USUARIO_INCORRECTO";
	public static final String LOGIN_CONTRASENA_INCORRECTO = "LOGIN_CONTRASENA_INCORRECTO";
	public static final String LOGIN_CORRECTO = "LOGIN_CORRECTO";

	public static final String DNI_PERSONA_VACIO = "DNI_PERSONA_VACIO";
	public static final String DNI_PERSONA_ALFANUMERICO_INCORRECTO = "DNI_PERSONA_INCORRECTO";
	public static final String DNI_PERSONA_MENOR_QUE_9 = "DNI_PERSONA_MENOR_QUE_9";
	public static final String DNI_PERSONA_MAYOR_QUE_9 = "DNI_PERSONA_MAYOR_QUE_9";
	public static final String DNI_PERSONA_NO_VALIDO = "DNI_PERSONA_NO_VALIDO";

	public static final String NOMBRE_VACIO = "NOMBRE_VACIO";
	public static final String NOMBRE_LETRAS_ACENTOS_INCORRECTO = "NOMBRE_LETRAS_ACENTOS_INCORRECTO";
	public static final String NOMBRE_MENOR_QUE_3 = "NOMBRE_MENOR_QUE_3";
	public static final String NOMBRE_MAYOR_QUE_56 = "NOMBRE_MAYOR_QUE_56";
	public static final String NOMBRE_PERSONA_NUMERICO = "NOMBRE_PERSONA_NUMERICO";

	public static final String APELLIDOS_PERSONA_VACIO = "APELLIDOS_PERSONA_VACIO";
	public static final String APELLIDOS_PERSONA_LETRAS_ACENTOS_INCORRECTO = "APELLIDOS_PERSONA_ALFABETICO_INCORRECTO";
	public static final String APELLIDOS_PERSONA_MENOR_QUE_3 = "APELLIDOS_PERSONA_MENOR_QUE_3";
	public static final String APELLIDOS_PERSONA_MAYOR_QUE_128 = "APELLIDOS_PERSONA_MAYOR_QUE_128";
	public static final String APELLIDOS_PERSONA_NUMERICO = "APELLIDOS_PERSONA_NUMERICO";

	public static final String FECHA_NACIMIENTO_VACIA = "FECHA_NACIMIENTO_VACIA";
	public static final String FECHA_NACIMIENTO_NUMERICA_INCORRECTA = "FECHA_NACIMIENTO_NUMERICA_INCORRECTA";
	public static final String FECHA_NACIMIENTO_MENOR_QUE_8 = "FECHA_NACIMIENTO_MENOR_QUE_8";
	public static final String FECHA_NACIMIENTO_MAYOR_QUE_8 = "FECHA_NACIMIENTO_MAYOR_QUE_8";

	public static final String TELEFONO_VACIO = "TELEFONO_VACIO";
	public static final String TELEFONO_NUMERICO_INCORRECTO = "TELEFONO_NUMERICO_INCORRECTO";
	public static final String TELEFONO_MENOR_QUE_9 = "TELEFONO_MENOR_QUE_9";
	public static final String TELEFONO_MAYOR_QUE_9 = "TELEFONO_MAYOR_QUE_9";

	public static final String EMAIL_VACIO = "EMAIL_VACIO";
	public static final String EMAIL_ALFANUMERICO_INCORRECTO = "EMAIL_ALFANUMERICO_INCORRECTO";
	public static final String EMAIL_MENOR_QUE_4 = "EMAIL_MENOR_QUE_4";
	public static final String EMAIL_MAYOR_QUE_48 = "EMAIL_MAYOR_QUE_48";

	public static final String DIRECCION_VACIO = "DIRECCION_VACIO";
	public static final String DIRECCION_MENOR_QUE_3 = "DIRECCION_MENOR_QUE_3";
	public static final String DIRECCION_MAYOR_QUE_128 = "DIRECCION_MAYOR_QUE_128";

	public static final String CIF_EMPRESA_VACIO = "CIF_EMPRESA_VACIO";
	public static final String CIF_EMPRESA_ALFANUMERICO_INCORRECTO = "CIF_EMPRESA_ALFANUMERICO_INCORRECTO";
	public static final String CIF_EMPRESA_MENOR_QUE_9 = "CIF_EMPRESA_MENOR_QUE_9";
	public static final String CIF_EMPRESA_MAYOR_QUE_9 = "CIF_EMPRESA_MAYOR_QUE_9";

	public static final String ROL_NAME_VACIO = "ROL_NAME_VACIO";
	public static final String ROL_NAME_ALFABETICO_INCORRECTO = "ROL_NAME_ALFABETICO_INCORRECTO";
	public static final String ROL_NAME_MENOR_QUE_3 = "ROL_NAME_MENOR_QUE_3";
	public static final String ROL_NAME_MAYOR_QUE_32 = "ROL_NAME_MAYOR_QUE_32";

	public static final String ROL_DESCRIPTION_VACIO = "ROL_DESCRIPTION_VACIO";
	public static final String ROL_DESCRIPTION_ALFABETICO_INCORRECTO = "ROL_DESCRIPTION_ALFABETICO_INCORRECTO";
	public static final String ROL_DESCRIPTION_MENOR_QUE_3 = "ROL_DESCRIPTION_MENOR_QUE_3";

	public static final String ACCION_NAME_VACIO = "ACCION_NAME_VACIO";
	public static final String ACCION_NAME_ALFABETICO_INCORRECTO = "ACCION_NAME_ALFABETICO_INCORRECTO";
	public static final String ACCION_NAME_MENOR_QUE_3 = "ACCION_NAME_MENOR_QUE_3";
	public static final String ACCION_NAME_MAYOR_QUE_48 = "ACCION_NAME_MAYOR_QUE_48";

	public static final String ACCION_DESCRIPTION_VACIO = "ACCION_DESCRIPTION_VACIO";
	public static final String ACCION_DESCRIPTION_ALFABETICO_INCORRECTO = "ACCION_DESCRIPTION_ALFABETICO_INCORRECTO";
	public static final String ACCION_DESCRIPTION_MENOR_QUE_3 = "ACCION_DESCRIPTION_MENOR_QUE_3";

	public static final String ACCION_VACIA = "ACCION_VACIA";

	public static final String FUNCIONALIDAD_NAME_VACIA = "FUNCIONALIDAD_NAME_VACIA";
	public static final String FUNCIONALIDAD_NAME_ALFABETICO_INCORRECTO = "FUNCIONALIDAD_NAME_ALFABETICO_INCORRECTO";
	public static final String FUNCIONALIDAD_NAME_MENOR_QUE_3 = "FUNCIONALIDAD_NAME_MENOR_QUE_3";
	public static final String FUNCIONALIDAD_NAME_MAYOR_QUE_48 = "FUNCIONALIDAD_NAME_MAYOR_QUE_48";

	public static final String FUNCIONALIDAD_DESCRIPTION_VACIA = "FUNCIONALIDAD_DESCRIPTION_VACIA";
	public static final String FUNCIONALIDAD_DESCRIPTION_ALFABETICO_INCORRECTO = "FUNCIONALIDAD_DESCRIPTION_ALFABETICO_INCORRECTO";
	public static final String FUNCIONALIDAD_DESCRIPTION_MENOR_QUE_3 = "FUNCIONALIDAD_DESCRIPTION_MENOR_QUE_3";

	public static final String FUNCIONALIDAD_VACIA = "FUNCIONALIDAD_VACIA";

	public static final String OBJETIVO_NAME_VACIO = "OBJETIVO_NAME_VACIO";
	public static final String OBJETIVO_NAME_ALFABETICO_INCORRECTO = "OBJETIVO_NAME_ALFABETICO_INCORRECTO";
	public static final String OBJETIVO_NAME_MENOR_QUE_3 = "OBJETIVO_NAME_MENOR_QUE_3";
	public static final String OBJETIVO_NAME_MAYOR_QUE_48 = "OBJETIVO_NAME_MAYOR_QUE_48";

	public static final String OBJETIVO_DESCRIPTION_VACIO = "OBJETIVO_DESCRIPTION_VACIO";
	public static final String OBJETIVO_DESCRIPTION_ALFABETICO_INCORRECTO = "OBJETIVO_DESCRIPTION_ALFABETICO_INCORRECTO";
	public static final String OBJETIVO_DESCRIPTION_MENOR_QUE_3 = "OBJETIVO_DESCRIPTION_MENOR_QUE_3";

	public static final String OBJETIVO_VACIO = "OBJETIVO_VACIO";

	public static final String TEXTO_RESPUESTA_VACIO = "TEXTO_RESPUESTA_VACIO";
	public static final String TEXTO_RESPUESTA_ALFANUMERICO_SIGNOS_PUNTUACION_INCORRECTO = "TEXTO_RESPUESTA_ALFANUMERICO_SIGNOS_PUNTUACION_INCORRECTO";
	public static final String TEXTO_RESPUESTA_MENOR_QUE_2 = "TEXTO_RESPUESTA_MENOR_QUE_2";

	public static final String FECHA_RESPUESTA_VACIA = "FECHA_RESPUESTA_VACIA";

	public static final String RESPUESTA_POSIBLE_VACIA = "RESPUESTA_POSIBLE_VACIA";

	public static final String USUARIO_VACIO = "USUARIO_VACIO";
	public static final String ROL_USUARIO_MODIFICADO_OK = "ROL_USUARIO_MODIFICADO_OK";

	public static final String PERSONA_AÑADIR_VACIA = "PERSONA_AÑADIR_VACIA";

	public static final String REGISTRO_CORRECTO = "REGISTRO_CORRECTO";
	public static final String REGISTRO_VACIO = "REGISTRO_VACIO";
	public static final String REGISTRO_PERSONA_EXISTE = "REGISTRO_PERSONA_EXISTE";
	public static final String REGISTRO_USUARIO_EXISTE = "REGISTRO_USUARIO_EXISTE";
	public static final String REGISTRO_EMPRESA_EXISTE = "REGISTRO_EMPRESA_EXISTE";
	public static final String REGISTRO_PERSONA_VACIA = "REGISTRO_PERSONA_VACIA";
	public static final String REGISTRO_USUARIO_VACIO = "REGISTRO_USUARIO_VACIO";
	public static final String REGISTRO_EMPRESA_VACIA = "REGISTRO_EMPRESA_VACIA";

	public static final String ROL_VACIO = "ROL_VACIO";
	public static final String ROL_NO_EXISTE = "ROL_NO_EXISTE";
	public static final String BUSCAR_ROL_CORRECTO = "BUSCAR_ROL_CORRECTO";
	public static final String GUARDAR_ROL_CORRRECTO = "GUARDAR_ROL_CORRECTO";
	public static final String GUARDAR_ROL_VACIO = "GUARDAR_ROL_VACIO";
	public static final String GUARDAR_ROL_YA_EXISTE = "GUARDAR_ROL_YA_EXISTE";
	public static final String ELIMINAR_ROL_CORRECTO = "ELIMINAR_ROL_CORRECTO";
	public static final String ELIMINAR_ROL_ASOCIADO_USUARIO = "ELIMINAR_ROL_ASOCIADO_USUARIO";
	public static final String ELIMINAR_ROL_ASOCIADO_ACCION_FUNCIONALIDAD = "ELIMINAR_ROL_ASOCIAO_ACCION_FUNCIONALIDAD";
	public static final String MODIFICAR_ROL = "MODIFICAR_ROL";
	public static final String REACTIVAR_ROL_CORRECTO = "REACTIVAR_ROL_CORRECTO";

	public static final String ACCION_NO_EXISTE = "ACCION_NO_EXISTE";
	public static final String BUSCAR_ACCION_CORRECTO = "BUSCAR_ACCION_CORRECTO";
	public static final String ACCION_YA_EXISTE = "ACCION_YA_EXISTE";
	public static final String GUARDAR_ACCION_CORRECTO = "GUARDAR_ACCION_CORRECTO";
	public static final String MODIFICAR_ACCION_CORRECTO = "MODIFICAR_ACCION_CORRECTO";
	public static final String ELIMINAR_ACCION_CORRECTO = "ELIMINAR_ACCION_CORRECTO";
	public static final String ELIMINAR_ACCION_ASOCIADA_ROL_FUNCIONALIDAD = "ELIMINAR_ACCION_ASOCIADA_ROL_FUNCIONALIDAD";
	public static final String REACTIVAR_ACCION_CORRECTO = "REACTIVAR_ACCION_CORRECTO";
	public static final String ASIGNAR_ACCION_CORRECTO = "ASIGNAR_ACCION_CORRECTO";
	public static final String ACCION_REVOCADA_CORRECTO = "ACCION_REVOCADA_CORRECTO";

	public static final String FUNCIONALIDAD_NO_EXISTE = "FUNCIONALIDAD_NO_EXISTE";
	public static final String BUSCAR_FUNCIONALIDAD_CORRECTO = "BUSCAR_FUNCIONALIDAD_CORRECTO";
	public static final String FUNCIONALIDAD_YA_EXISTE = "FUNCIONALIDAD_YA_EXISTE";
	public static final String GUARDAR_FUNCIONALIDAD_CORRECTO = "GUARDAR_FUNCIONALIDAD_CORRECTO";
	public static final String MODIFICAR_FUNCIONALIDAD_CORRECTO = "MODIFICAR_FUNCIONALIDAD_CORRECTO";
	public static final String ELIMINAR_FUNCIONALIDAD_CORRECTO = "ELIMINAR_FUNCIONALIDAD_CORRECTO";
	public static final String ELIMINAR_FUNCIONALIDAD_ASOCIADA_ROL_ACCION = "ELIMINAR_FUNCIONALIDAD_ASOCIADA_ROL_ACCION";
	public static final String REACTIVAR_FUNCIONALIDAD_CORRECTO = "REACTIVAR_FUNCIONALIDAD_CORRECTO";

	public static final String BUSCAR_USUARIO_CORRECTO = "BUSCAR_USUARIO_CORRECTO";
	public static final String ELIMINAR_USUARIO_CORRECTO = "ELIMINAR_USUARIO_CORRECTO";
	public static final String USUARIO_NO_ENCONTRADO = "USUARIO_NO_ENCONTRADO";
	public static final String CONTRASEÑA_MODIFICADA_OK = "CONTRASEÑA_MODIFICADA_OK";
	public static final String REACTIVAR_USUARIO_CORRECTO = "REACTIVAR_USUARIO_CORRECTO";

	public static final String BUSCAR_EMPRESA_CORRECTO = "BUSCAR_EMPRESA_CORRECTO";
	public static final String EMPRESA_VACIA = "EMPRESA_VACIA";
	public static final String GUARDAR_EMPRESA_CORRECTO = "GUARDAR_EMPRESA_CORRECTO";
	public static final String EMPRESA_YA_EXISTE = "EMPRESA_YA_EXISTE";
	public static final String MODIFICAR_EMPRESA_CORRECTO = "MODIFICAR_EMPRESA_CORRECTO";
	public static final String EMPRESA_NO_EXISTE = "EMPRESA_NO_EXISTE";
	public static final String ELIMINAR_EMPRESA_CORRECTO = "ELIMINAR_EMPRESA_CORRECTO";
	public static final String EMPRESA_ASOCIADA_PERSONAS = "EMPRESA_ASOCIADAS_PERSONAS";
	public static final String REACTIVAR_EMPRESA_CORRECTO = "REACTIVAR_EMPRESA_CORRECTO";

	public static final String BUSCAR_PERSONA_CORRECTO = "BUSCAR_PERSONA_CORRECTO";
	public static final String PERSONA_YA_EXISTE = "PERSONA_YA_EXISTE";
	public static final String USUARIO_YA_EXISTE = "USUARIO_YA_EXISTE";
	public static final String GUARDAR_PERSONA_CORRECTO = "GUARDAR_PERSONA_CORRECTO";
	public static final String ELIMINAR_PERSONA_CORRECTO = "ELIMINAR_PERSONA_CORRECTO";
	public static final String PERSONA_NO_EXISTE = "PERSONA_NO_EXISTE";
	public static final String MODIFICAR_PERSONA_CORRECTO = "MODIFICAR_PERSONA_CORRECTO";
	public static final String REACTIVAR_PERSONA_CORRECTO = "REACTIVAR_PERSONA_CORRECTO";

	public static final String MAIL_NO_ENVIADO = "MAIL_NO_ENVIADO";
	public static final String RECUPERAR_CONTRASEÑA_CORRECTO = "RECUPERAR_CONTRASEÑA_CORRECTO";
	public static final String MAIL_NO_ENCONTRADO = "MAIL_NO_ENCONTRADO";

	public static final String PERMISO_NO_EXISTE = "PERMISO_NO_EXISTE";

	public static final String TITULO_NOTICIA_VACIO = "TITULO_NOTICIA_VACIO";
	public static final String TITULO_NOTICIA_ALFABETICO_INCORRECTO = "TITULO_NOTICIA_ALFABETICO_INCORRECTO";
	public static final String TITULO_NOTICIA_MENOR_QUE_3 = "TITULO_NOTICIA_MENOR_QUE_3";
	public static final String TITULO_NOTICIA_MAYOR_QUE_256 = "TITULO_NOTICIA_MAYOR_QUE_256";

	public static final String TEXTO_NOTICIA_VACIO = "TEXTO_NOTICIA_VACIO";
	public static final String TEXTO_NOTICIA_ALFANMERICO_SIGNOS_PUNTUACION_INCORRECTO = "TEXTO_NOTICIA_ALFANMERICO_SIGNOS_PUNTUACION_INCORRECTO";
	public static final String TEXTO_NOTICIA_MENOR_QUE_3 = "TEXTO_NOTICIA_MENOR_QUE_3";

	public static final String FECHA_NOTICIA_VACIA = "FECHA_NOTICIA_VACIA";
	public static final String FECHA_NOTICIA_NUMERICA_INCORRECTA = "FECHA_NOTICIA_NUMERICA_INCORRECTA";
	public static final String FECHA_NOTICIA_MENOR_QUE_8 = "FECHA_NOTICIA_MENOR_QUE_8";
	public static final String FECHA_NOTICIA_MAYOR_QUE_8 = "FECHA_NOTICIA_MAYOR_QUE_8";

	public static final String NOTICIA_VACIA = "noticiaVacia";

	public static final String BUSCAR_NOTICIA_CORRECTO = "BUSCAR_NOTICIA_CORRECTO";
	public static final String NOTICIA_YA_EXISTE = "NOTICIA_YA_EXISTE";
	public static final String NOTICIA_NO_EXISTE = "NOTICIA_NO_EXISTE";
	public static final String GUARDAR_NOTICIA_CORRECTO = "GUARDAR_NOTICIA_CORRECTO";
	public static final String MODIFICAR_NOTICIA_CORRECTO = "MODIFICAR_NOTICIA_CORRECTO";
	public static final String ELIMINAR_NOTICIA_CORRECTO = "ELIMINAR_NOTICIA_CORRECTO";

	public static final String BUSCAR_OBJETIVO_CORRECTO = "BUSCAR_OBJETIVO_CORRECTO";
	public static final String OBJETIVO_YA_EXISTE = "OBJETIVO_YA_EXISTE";
	public static final String OBJETIVO_NO_EXISTE = "OBJETIVO_NO_EXISTE";
	public static final String GUARDAR_OBJETIVO_CORRECTO = "GUARDAR_OBJETIVO_CORRECTO";
	public static final String MODIFICAR_OBJETIVO_CORRECTO = "MODIFICAR_OBJETIVO_CORRECTO";
	public static final String ELIMINAR_OBJETIVO_CORRECTO = "ELIMINAR_OBJETIVO_CORRECTO";
	public static final String REACTIVAR_OBJETIVO_CORRECTO = "REACTIVAR_OBJETIVO_CORRECTO";

	public static final String BUSCAR_RESPUESTA_POSIBLE_CORRECTO = "BUSCAR_RESPUESTA_POSIBLE_CORRECTO";
	public static final String RESPUESTA_POSIBLE_YA_EXISTE = "RESPUESTA_POSIBLE_YA_EXISTE";
	public static final String RESPUESTA_POSIBLE_NO_EXISTE = "RESPUESTA_POSIBLE_NO_EXISTE";
	public static final String GUARDAR_RESPUESTA_POSIBLE_CORRECTO = "GUARDAR_RESPUESTA_POSIBLE_CORRECTO";
	public static final String MODIFICAR_RESPUESTA_POSIBLE_CORRECTO = "MODIFICAR_RESPUESTA_POSIBLE_CORRECTO";
	public static final String ELIMINAR_RESPUESTA_POSIBLE_CORRECTO = "ELIMINAR_RESPUESTA_POSIBLE_CORRECTO";
	public static final String ELIMINAR_RESPUESTA_POSIBLE_ASOCIADA_PROCESO = "ELIMINAR_RESPUESTA_POSIBLE_ASOCIADA_PROCESO";
	public static final String REACTIVAR_RESPUESTA_POSIBLE_CORRECTO = "REACTIVAR_RESPUESTA_POSIBLE_CORRECTO";

}
