package com.sds.service.common;

public class CodigosMensajes {

	public static final String LOGIN_USUARIO_VACIO = "LOGIN_USUARIO_VACIO";
	public static final String LOGIN_ALFANUMERICO_INCORRECTO = "LOGIN_ALFANUMERICO_INCORRECTO";
	public static final String LOGIN_MENOR_QUE_3 = "LOGIN_MENOR_QUE_3";
	public static final String LOGIN_MAYOR_QUE_45 = "LOGIN_MAYOR_QUE_45";

	public static final String PASS_USUARIO_VACIO = "PASS_USUARIO_VACIO";
	public static final String PASS_ALFANUMERICO_INCORRECTO = "PASS_ALFANUMERICO_INCORRECTO";
	public static final String PASS_MENOR_QUE_3 = "PASS_MENOR_QUE_3";
	public static final String PASS_MAYOR_QUE_45 = "PASS_MAYOR_QUE_45";

	public static final String LOGIN_USUARIO_INCORRECTO = "LOGIN_USUARIO_INCORRECTO";
	public static final String LOGIN_CONTRASENA_INCORRECTO = "LOGIN_CONTRASENA_INCORRECTO";
	public static final String LOGIN_CORRECTO = "LOGIN_CORRECTO";

	public static final String DNI_PERSONA_VACIO = "DNI_PERSONA_VACIO";
	public static final String DNI_PERSONA_ALFANUMERICO_INCORRECTO = "DNI_PERSONA_INCORRECTO";
	public static final String DNI_PERSONA_MENOR_QUE_9 = "DNI_PERSONA_MENOR_QUE_9";
	public static final String DNI_PERSONA_MAYOR_QUE_9 = "DNI_PERSONA_MAYOR_QUE_9";

	public static final String NOMBRE_VACIO = "NOMBRE_VACIO";
	public static final String NOMBRE_LETRAS_ACENTOS_INCORRECTO = "NOMBRE_LETRAS_ACENTOS_INCORRECTO";
	public static final String NOMBRE_MENOR_QUE_3 = "NOMBRE_MENOR_QUE_3";
	public static final String NOMBRE_MAYOR_QUE_56 = "NOMBRE_MAYOR_QUE_56";
	public static final String NOMBRE_PERSONA_NUMERICO = "NOMBRE_PERSONA_NUMERICO";

	public static final String APELLIDOS_PERSONA_VACIO = "APELLIDOS_PERSONA_VACIO";
	public static final String APELLIDOS_PERSONA_LETRAS_ACENTOS_INCORRECTO = "APELLIDOS_PERSONA_ALFABETICO_INCORRECTO";
	public static final String APELLIDOS_PERSONA_MENOR_QUE_3 = "APELLIDOS_PERSONA_MENOR_QUE_3";
	public static final String APELLIDOS_PERSONA_MAYOR_QUE_128 = "APELLIDOS_PERSONA_MAYOR_QUE_128";
	public static final String APELLIDOS_PERSONA_NUMERICO = "APELLIDOS_PERSONA_NUMERICO";

	public static final String FECHA_NACIMIENTO_VACIA = "FECHA_NACIMIENTO_VACIA";
	public static final String FECHA_NACIMIENTO_NUMERICA_INCORRECTA = "FECHA_NACIMIENTO_NUMERICA_INCORRECTA";
	public static final String FECHA_NACIMIENTO_MENOR_QUE_8 = "FECHA_NACIMIENTO_MENOR_QUE_8";
	public static final String FECHA_NACIMIENTO_MAYOR_QUE_8 = "FECHA_NACIMIENTO_MAYOR_QUE_8";

	public static final String TELEFONO_VACIO = "TELEFONO_VACIO";
	public static final String TELEFONO_NUMERICO_INCORRECTO = "TELEFONO_NUMERICO_INCORRECTO";
	public static final String TELEFONO_MENOR_QUE_9 = "TELEFONO_MENOR_QUE_9";
	public static final String TELEFONO_MAYOR_QUE_9 = "TELEFONO_MAYOR_QUE_9";

	public static final String EMAIL_VACIO = "EMAIL_VACIO";
	public static final String EMAIL_ALFANUMERICO_INCORRECTO = "EMAIL_ALFANUMERICO_INCORRECTO";
	public static final String EMAIL_MENOR_QUE_4 = "EMAIL_MENOR_QUE_4";
	public static final String EMAIL_MAYOR_QUE_48 = "EMAIL_MAYOR_QUE_48";

	public static final String DIRECCION_VACIO = "DIRECCION_VACIO";
	public static final String DIRECCION_MENOR_QUE_3 = "DIRECCION_MENOR_QUE_3";
	public static final String DIRECCION_MAYOR_QUE_128 = "DIRECCION_MAYOR_QUE_128";

	public static final String CIF_EMPRESA_VACIO = "CIF_EMPRESA_VACIO";
	public static final String CIF_EMPRESA_ALFANUMERICO_INCORRECTO = "CIF_EMPRESA_ALFANUMERICO_INCORRECTO";
	public static final String CIF_EMPRESA_MENOR_QUE_9 = "CIF_EMPRESA_MENOR_QUE_9";
	public static final String CIF_EMPRESA_MAYOR_QUE_9 = "CIF_EMPRESA_MAYOR_QUE_9";

	public static final String ROL_NAME_VACIO = "ROL_NAME_VACIO";
	public static final String ROL_NAME_ALFABETICO_INCORRECTO = "ROL_NAME_ALFABETICO_INCORRECTO";
	public static final String ROL_NAME_MENOR_QUE_3 = "ROL_NAME_MENOR_QUE_3";
	public static final String ROL_NAME_MAYOR_QUE_32 = "ROL_NAME_MAYOR_QUE_32";

	public static final String ROL_DESCRIPTION_VACIO = "ROL_DESCRIPTION_VACIO";
	public static final String ROL_DESCRIPTION_ALFABETICO_INCORRECTO = "ROL_DESCRIPTION_ALFABETICO_INCORRECTO";
	public static final String ROL_DESCRIPTION_MENOR_QUE_3 = "ROL_DESCRIPTION_MENOR_QUE_3";

	public static final String ACCION_NAME_VACIO = "ACCION_NAME_VACIO";
	public static final String ACCION_NAME_ALFABETICO_INCORRECTO = "ACCION_NAME_ALFABETICO_INCORRECTO";
	public static final String ACCION_NAME_MENOR_QUE_3 = "ACCION_NAME_MENOR_QUE_3";
	public static final String ACCION_NAME_MAYOR_QUE_48 = "ACCION_NAME_MAYOR_QUE_48";

	public static final String ACCION_DESCRIPTION_VACIO = "ACCION_DESCRIPTION_VACIO";
	public static final String ACCION_DESCRIPTION_ALFABETICO_INCORRECTO = "ACCION_DESCRIPTION_ALFABETICO_INCORRECTO";
	public static final String ACCION_DESCRIPTION_MENOR_QUE_3 = "ACCION_DESCRIPTION_MENOR_QUE_3";

	public static final String ACCION_VACIA = "ACCION_VACIA";

	public static final String REGISTRO_CORRECTO = "REGISTRO_CORRECTO";
	public static final String REGISTRO_VACIO = "REGISTRO_VACIO";
	public static final String REGISTRO_PERSONA_EXISTE = "REGISTRO_PERSONA_EXISTE";
	public static final String REGISTRO_USUARIO_EXISTE = "REGISTRO_USUARIO_EXISTE";
	public static final String REGISTRO_EMPRESA_EXISTE = "REGISTRO_EMPRESA_EXISTE";
	public static final String REGISTRO_PERSONA_VACIA = "REGISTRO_PERSONA_VACIA";
	public static final String REGISTRO_USUARIO_VACIO = "REGISTRO_USUARIO_VACIO";
	public static final String REGISTRO_EMPRESA_VACIA = "REGISTRO_EMPRESA_VACIA";
	public static final String ROL_VACIO = "ROL_VACIO";
	public static final String ROL_NO_EXISTE = "ROL_NO_EXISTE";
	public static final String BUSCAR_ROL_CORRECTO = "BUSCAR_ROL_CORRECTO";
	public static final String GUARDAR_ROL_CORRRECTO = "GUARDAR_ROL_CORRECTO";
	public static final String GUARDAR_ROL_VACIO = "GUARDAR_ROL_VACIO";
	public static final String GUARDAR_ROL_YA_EXISTE = "GUARDAR_ROL_YA_EXISTE";
	public static final String ELIMINAR_ROL_CORRECTO = "ELIMINAR_ROL_CORRECTO";
	public static final String ELIMINAR_ROL_ASOCIADO_USUARIO = "ELIMINAR_ROL_ASOCIADO_USUARIO";
	public static final String MODIFICAR_ROL = "MODIFICAR_ROL";
	public static final String ACCION_NO_EXISTE = "ACCION_NO_EXISTE";
	public static final String BUSCAR_ACCION_CORRECTO = "BUSCAR_ACCION_CORRECTO";
	public static final String ACCION_YA_EXISTE = "ACCION_YA_EXISTE";
	public static final String GUARDAR_ACCION_CORRECTO = "GUARDAR_ACCION_CORRECTO";
	public static final String MODIFICAR_ACCION_CORRECTO = "MODIFICAR_ACCION_CORRECTO";
	public static final String ELIMINAR_ACCION_CORRECTO = "ELIMINAR_ACCION_CORRECTO";
	public static final String ELIMINAR_ACCION_ASOCIADA_ROL_FUNCIONALIDAD = "ELIMINAR_ACCION_ASOCIADA_ROL_FUNCIONALIDAD";

}
